"""Second

Revision ID: 0b3c1322c687
Revises: 461dbbe70f24
Create Date: 2025-09-26 20:44:05.262396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3c1322c687'
down_revision = '461dbbe70f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
