"""Third

Revision ID: 1b2ba3e6ba02
Revises: 0b3c1322c687
Create Date: 2025-09-26 20:52:14.593750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2ba3e6ba02'
down_revision = '0b3c1322c687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
