"""Fourth

Revision ID: 23af9f717dfd
Revises: 1b2ba3e6ba02
Create Date: 2025-09-26 21:14:56.417293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23af9f717dfd'
down_revision = '1b2ba3e6ba02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
