"""Initial

Revision ID: 461dbbe70f24
Revises: 5a1322ea9fc2
Create Date: 2025-09-26 20:42:17.672475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461dbbe70f24'
down_revision = '5a1322ea9fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
